### ISSUE TITLE
Assignment preview fails to render

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#118]
Clicking the preview option for an assignment doesn't work:

![Screenshot from 2022-12-07 17-06-17](https://user-images.githubusercontent.com/796053/206230238-4c9b7f3f-5b2b-440a-a4b8-3cb28c193dc3.png)

The HTTP 500 has a `KeyError` for line 368 in `trix/trix_admin/views/assignments.py` with the following message: `KeyError: 'pk'`

Edit: I have tested by adding myself (sysadmin) as a admin of the course just in case.

**Comment by Levijatan** [comment]
Fixed

**Comment by torgeirl** [comment]
Solved in 3.0.0b14 :+1:
