### ISSUE TITLE
Improve contrast

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#121]
Alongside upgrading Django from 3.2 to 4.2 (#119) we need to address issues with too low contrast.

Known issues as of 3.0.0b.16:
* the `DevilryCommentEditor` (added to solve #19)
* course admin assignment overview page

**Comment by Levijatan** [comment]
The course admin assignment overview page contrast error seems to be a false positive. Because of how the menu is implemented it takes the colour of the element behind the menu background not the menu background colour. Trix probably could use a refactor of the ui.

**Comment by Levijatan** [comment]
Fixed the contrast issues I could find inn editor and course admin assignment overview page
9a22163
