### ISSUE TITLE
Health check endpoint

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#135]
When hosting Trix as a service in a container orchestration environment, the service will need to answer health checks quite often. Doing these against the `/` endpoint will clutter the access logs. A better approach is to have a dedicated endpoint, i.e. `/health`. This way, the production environment can use a `logging.Filter` to do disable access logging for `/health` endpoint so it never enters the logging infrastructure (ELK, etc).

[The implementation included in Devilry 6.0.0rc2](https://github.com/devilry/devilry-django/commit/db73aa144aa3dd8b64dee0362677bd107be80664) should be a good starting point; hopefully it can be re-used with just small modifications (Devilry issue: https://github.com/devilry/devilry-django/issues/1261).

**Comment by Levijatan** [comment]
Pretty much reused as much as possible from devilry so there is now 2 new api endpoints at '_api/application-state/ready' and '_api/application-state/alive'. 7fdbc91. 'ready' checks if the db is up, and 'alive' just returns 200.

**Comment by torgeirl** [comment]
Perfect! :+1:
