### ISSUE TITLE
Remove `REDIRECT_URL`s from default settings

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#141]
`trix/project/default/settings.py` includes default redirect URLs for logins and logouts:

```
# Redirect logins and logouts to the frontpage by default
LOGIN_REDIRECT_URL = '/'
LOGOUT_REDIRECT_URL = '/'
```

These are probably not helping with #126, and should probably have be removed alongside #27.

**Comment by Levijatan** [comment]
Removed in cdcc742

**Comment by torgeirl** [comment]
Looks like we instead of removing these should set them to fallbacks when what is needed for `next` to work is missing. Working on identifying what those fallbacks should be.
