### ISSUE TITLE
Remove obsolete middleware

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#144]
There are two instances of `django.middleware.clickjacking.XFrameOptionsMiddleware` in `trix/project/default/settings.py`; judging from [Django's documentation](https://docs.djangoproject.com/en/4.2/topics/http/middleware/#activating-middleware) the [first instance (line 66)](https://github.com/devilry/trix2/blob/4.0.0/trix/project/default/settings.py#L66) should be removed.

Edit: we actually want to remove both instances `django.middleware.clickjacking.XFrameOptionsMiddleware` since its inclusion trumps the changes in #140; from [the documentation](https://docs.djangoproject.com/en/4.2/ref/clickjacking/#setting-x-frame-options-for-all-responses):
> By default, the middleware will set the `X-Frame-Options` header to `DENY` for every outgoing `HttpResponse`.

**Comment by Levijatan** [comment]
Removed in 259e517
