### ISSUE TITLE
Python 2 to Python 3

### ISSUE THREAD

**Issue by Elthan** [devilry/trix2#38]
Upgrade from python 2 to python 3.

Python 2 will be deprecated and python 3 will be required from Django v2.0.

**Comment by torgeirl** [comment]
This should probably be done when upgrading from Django 1.11 LTS to 2.2 LTS.

The window for this would be April 2019 (2.2 release) - April 2020 (1.11 end-of-life).

**Comment by torgeirl** [comment]
Some guides for Python 2 to Python 3 code transformation:
- https://docs.python.org/2/library/2to3.html
- http://python3porting.com/2to3.html

(Copied from [Devilry's update issue](https://github.com/devilry/devilry-django/issues/1103).)

**Comment by Elthan** [comment]
https://github.com/Elthan/trix2/tree/python3 - working example after conversion using automated tools and some manual modification to the code.

**Comment by torgeirl** [comment]
@Elthan: that looks very promising! :+1: I assume you've only be able to do limited testing? 

I'll see if we can involve some power users in testing it more widely, and more generally how we are planning to move forward.

**Comment by Elthan** [comment]
More or less, the version used in my masters (gamification branch) is built upon the python3 version, and that has worked fine.

Sounds good 👍

**Comment by tworide** [comment]
This seem to be merged and is working so i close this issue for milestone Trix 3
