### ISSUE TITLE
Separate solved statistic by semester

### ISSUE THREAD

**Issue by Elthan** [devilry/trix2#50]
Implement some way of separating statistics by semester. In addition to allowing admins to look at statistics for the semester they choose it would make it easier to implement deletion of data.

Suggested ways:
- Add a DateTime field to HowSolved and add filter to statistics page. This wouldn't work on previously solved assignments.
- Remodel how Course, HowSolved, and Assignment, to make it possible to filter HowSolved based on semester tags.

May be other and better ways.

**Comment by torgeirl** [comment]
@Elthan: as discussed, just adding the DateTime field and a from-to date selection to the statistics view should be sufficient. We could play around with some practical defaults, but for simplicity's sake having 'all' as the default should be fine.
