### ISSUE TITLE
Permalinks for single assignments

### ISSUE THREAD

**Issue by Elthan** [devilry/trix2#57]
Suggested feature, needs specification.
Have permalinks that can link to groups of single assignments, ex: assignments/2&3&4 (shows assignment 2,3, and 4, already implemented).
Needs some way of selecting assignments that you want to include in permalink. Could be done by having a list of assignments with multiselect and tag filtering.

**Comment by torgeirl** [comment]
The functionality is available, but the URLs will have to be constructed manually. Closing the issue since we don't plan to add UI for this.
