### ISSUE TITLE
Server error when adding user

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#61]
Add user leads to a 500 server error. I'm guessing this could be related to LDAP (and haven't had a chance to test it without LDAP).

`Add new user` requires an email address while `ldap_to_django_username()` / `django_to_ldap_username()` assumes django see a regular  username. Perhaps that's the problem.

**Comment by Elthan** [comment]
Looks like it is related to LDAP as I could not recreate the issue on a test server. Some logic to fix this could be implemented, but will not be a high priority since it should not be a critical issue (new users simply need to log in to be created when using LDAP).

**Comment by torgeirl** [comment]
I think a solution should just be to deactivate the `Add user` option when `AUTHENTICATION_BACKENDS` doesn't contain a non-LDAP backend. I'm unfamiliar with how that would be implemented, but believe something similar is done in Devilry.

**Comment by torgeirl** [comment]
It seems the issue was an old LDAP config. The issue is no longer present with the [current LDAP config](https://trix2.readthedocs.io/en/latest/sysadmin/deploy.html#ldap).
