### ISSUE TITLE
New users gets server error after login

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#66]
@Elthan: it seems the implementation of #21 doesn't taking into account first-time users: `null value in column "last_login" violates not-null constraint`.

**Comment by Elthan** [comment]
When do you get this and how?

**Comment by torgeirl** [comment]
I don't; users that hasn't logged into the server previously get a `500 noe gikk galt` message.

**Comment by torgeirl** [comment]
Should be solved by #68.
