### ISSUE TITLE
Slowness when filtering on dates in statistics page

### ISSUE THREAD

**Issue by Elthan** [devilry/trix2#72]
When filtering large amounts of assignments in the statistics page it takes a long time to load the page. 
Implementing a better or faster way to filter by dates would decrease the server load.

**Comment by torgeirl** [comment]
> When filtering large amounts of assignments in the statistics page it takes a long time to load the page.

As an example, selecting assignment on a big course (800+ assignments) with many students can take appx 60s in the current production environment (`(...)/statistics/?from=2021-01-01&to=2021-02-28`). The same task will take appx 50s in our current development environment using v3.0.0b13 (if gateway timeout is increased from the default 30s).

**Comment by Levijatan** [comment]
Started working on this before it was removed from the 4.1 milestone, and I have gotten it from about 5000-7000ms down to about 600ms in local testing for course with 800 assignments and 30 students with 10 bymyself, 10 withhelp, and 10 notsolved per assignment.  Pushed up in bac3ced.
