### ISSUE TITLE
Preview view fails due to KeyError

### ISSUE THREAD

**Issue by torgeirl** [devilry/trix2#89]
The call to `cradmin_legacy`'s `get_preview_data` made in [trix_admin/views/assignments.py](https://github.com/devilry/trix2/blob/master/trix/trix_admin/views/assignments.py#L365) fails due to a `KeyError`.

The transaction is set to be `/a/{roleid}/assignments/preview/{pk}` while the URL seems to `/a/{courseid}/assignments/preview/`.

**Comment by Elthan** [comment]
When is this error occurring?

**Comment by torgeirl** [comment]
@Elthan: I believe it's certain previews from the admin view. At least, that what the URL suggests.

**Comment by Elthan** [comment]
Ok, do you have an example or something I can look at?

**Comment by torgeirl** [comment]
I guess 5f58c5b2b2c8dacc4d33232068255f192c2a02be might be intended to address this issue.
